### ISSUE TITLE
Tracker to fix todo in #1160 snapshot PR

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#1188]
This issue is for tracking the TODO which needs to be fixed after merging #1160, this will be closed after fixing all the todo's
for easier tracking am adding the TODO list here from the PR

- [ ] Create PVC from PVC
- [ ]  Fix issues with snapshot/clone (512) limits #1098
- [ ]  Allow Parallel cloning and snapshots creation on one PVC/clone (Need to work on in-memory locking)
- [ ]  Improve/Add Documentation for snapshot and cloning
- [ ]  Check Anything Needed to support datapool
- [ ]  Add doc file for the commands
- [ ]  If required some code cleanup
- [ ]  Replace GetStoredImageID with GetImageAttributes in all places

**Comment by Madhu-1** [comment]
> Add a list of kernel versions that supports the deep-flatten feature

@dillaman @idryomov can you please help us to know the kernel version which supports the deep-flatten features.

**Comment by idryomov** [comment]
deep-flatten is supported starting with upstream 5.1 and RHEL 8.2.

**Comment by Madhu-1** [comment]
> deep-flatten is supported starting with upstream 5.1 and RHEL 8.2.

any exact version of RHEL 8.2? like `4.18.0-193` because we need to flatten the image if the kernel version is less than the required version.

**Comment by idryomov** [comment]
Yes, use `4.18.0-193`.  Technically it is in `4.18.0-154`, but going by released versions is better.

**Comment by Madhu-1** [comment]
@idryomov So we can flatten the rbd images before use if the kernel version is less than 4.18.0-154 ?

**Comment by idryomov** [comment]
I think it's better to use `4.18.0-193` as the cutoff version.

**Comment by Madhu-1** [comment]
> I think it's better to use `4.18.0-193` as the cutoff version.

Okay will consider it, Thanks @idryomov

**Comment by Madhu-1** [comment]
> This issue is for tracking the TODO which needs to be fixed after merging #1160, this will be closed after fixing all the todo's
> for easier tracking am adding the TODO list here from the PR
> 
> * [x]  Create PVC from PVC
> * [x]   Fix issues with snapshot/clone (510) limits #1098
> * [x]  Add list of kernel versions that supports deep-flatten feature
> * [ ]   Allow Parallel cloning and snapshots creation on one PVC/clone (Need to work on in-memory locking)
> * [x]   Check Anything Needed to support datapool
> * [x]   Add doc file for the commands
> * [x]   If required some code cleanup
> * [x]   Replace GetStoredImageID with GetImageAttributes in all places
> * [x]  Various calls to deleteImage does not need the rbdStatus check. That is only required when calling from DeleteVolume. Suggest a TODO to optimize the same outside of the deleteImage call Other callers: cleanUpSnapshot, createRBDClone, createBackingImage, checkFlatten
> * [x]  Handle Bigger size Restore and Clone

closing this one as  `* [ ]   Allow Parallel cloning and snapshots creation on one PVC/clone (Need to work on in-memory locking)` already tracked in #1230
