### ISSUE TITLE
 Tracker to fix todo in #394 CephFS  snapshot/Clone PR 

### ISSUE THREAD

**Issue by humblec** [ceph/ceph-csi#1242]
This issue is for tracking the TODO which needs to be fixed after merging #394 , this will be closed after fixing all the todo's
for easier tracking am adding the TODO list here from the PR

- [x]  Update Documentation
<del> Describing e2e documentation on snapshot create,delete, restore and PVC clone
<del>Update support matrix to describe  which ceph versions are supported 
- [x] Plugin restart collecting cluster information (subvolume info support.etc) by  code **( Deferred to v3.2.0)**
https://github.com/ceph/ceph-csi/pull/394#discussion_r457558680
- [x] <del>Address total snapshots current limit (400) (**via documentation)

- [x]  <del>Add backend validation for CephFS subvolumes in E2E
*) Also address https://github.com/ceph/ceph-csi/pull/394#discussion_r464251501 ( both cephfs and rbd)

- [x] <del>Move `getMonsAndClusterID` to util as both RBD and CephFS use it
- [x] Revalidate the error strings and CSI error returns. ( **Deferred to 3.2.0)**

**Comment by Madhu-1** [comment]
@humblec Adding E2E for TODO doesn't seem correct. Without E2E in #394 how to ensure that everything works fine?

**Comment by humblec** [comment]
> @humblec Adding E2E for TODO doesn't seem correct. Without E2E in #394 how to ensure that everything works fine?

Sure, the rook cluster upgrade made me to put it here in first place, but removing it from the list as we need to sort this out any way. thanks ! :+1:

**Comment by Madhu-1** [comment]
- [ ] Add test in upgrade e2e to create snapshot and clone from older PVC

**Comment by Madhu-1** [comment]
@humblec can you please add documentation for 400 snapshot limit in release notes

**Comment by Madhu-1** [comment]
> @humblec can you please add documentation for 400 snapshot limit in release notes

@humblec FYI this also needs to be updated  in current cephfs snapshot doc

**Comment by Madhu-1** [comment]
> Revalidate the error strings and CSI error returns. ( Deferred to 3.2.0)

as this is deferred to 3.2.0 moving this to next milestone

**Comment by humblec** [comment]
Closing this one for now as these are already addressed.
