### ISSUE TITLE
Enhance/Refactor E2E tests 

### ISSUE THREAD

**Issue by humblec** [ceph/ceph-csi#2178]
# Describe the feature you'd like to have #

Looking at the E2E, our deployment model for E2E tests is bit clumsy,  Repeated code and the sequential lay out of the code make very difficult to folllow and also make it hard to add more deployment logic in future. This is an enhancement request to make it more modular and clear.

Items planned to address:

- [x] Improve RBD deployment model and make it modular #2180
- [x] Improve CephFS deployment model and make it modular #2180 
- [ ] Improve Vault deployment
- [ ] Make use of wrappers if possible in dpeloyment/test methods
- [ ] Make use of `storage/utils` framework methods for various operations which are kind of readymade for storage operations
- [ ] Try to make use of `LoadManifests()`, `createManifests()`, `PathItems()` methods instad of our own functions.
- [ ] Change object recreation logic in each test for StroageClass
- [ ] Modularize snapshot test cases 
- [ ] revisit each tests and improve the execution time and code modularity
- [x] Get rid of `waitGroup` passing between operations #2215 
- [ ] Dont block on `delete` operations in sender.
  For example: 
  
```
for i := 0; i < totalCount; i++ {
	name := fmt.Sprintf("%s%d", f.UniqueName, i)
	err = deletePVCAndApp(name, f, pvc, app)
	if err != nil {
			e2elog.Failf("failed to delete PVC or application with error %v", err)
	}
}
```

The waitTime goes `totalCount*` * `deploytimeout` in case there is an error in helper func, Instead of this spawn go routines and when we `receive` errors ( in some cases in first error itself)  in a channel , fail//exit.
- [ ] Create a task dispatcher which is capable of emitting and receiving requests/responses asynchronouly -> This could improve the code and also execution time drastically.
- [ ] Get rid of slice of `wgErr` to receive errors from helpers
- [ ] .... more to add

**Comment by nixpanic** [comment]
Indeed! There are also several tests that modify the StorageClass with additional/different options. This should get simplified so the deletion and re-creation of the StorageClass is not so bulky anymore.

I suggest doing something like:

```go
By(...) ... {
    withStorageClass(..., options map[string]string) ... {
        ...
    }
}
```

Where `withStorageClass()` then deletes the existing default StorageClass, and recreates it with the given options, runs the inner function and restores the original StorageClass.

Not sure what you are planning for other deployment options, but maybe you can use the same workflow as the e2e framework does.

**Comment by humblec** [comment]
@nixpanic looking at the E2E code, I see a good room for improvement which is really required anyway.  I will start one by one and would like to refactor it one by one.  The first PR I am planning to place it for RBD deployment from templates, that part itself looks clobbered. May be I will quickly drop a PR for it , so that we can have further discussions and continue improving one by one.

**Comment by nixpanic** [comment]
Sure, lots of improvements can be made. It helps to create a list of them in the issue description and be able to

- [x] check them (#2180)
- [ ] when they are done

Just make sure to not use `Fixes: #2178` in the PR description or commit message, use `Updates: #2178` instead.

In general, the e2e testing code should have the same quality standard (including linters that suggest simplification) as the rest of the project.

**Comment by humblec** [comment]
@nixpanic @Madhu-1 2180 is ready for review which addresses first 2 check boxes here in this issue. Please take a look :+1:
