### ISSUE TITLE
[Tracker ] Move listed features from Alpha -> Beta and Beta-> GA

### ISSUE THREAD

**Issue by humblec** [ceph/ceph-csi#2199]
# Describe the feature you'd like to have #

At present, we have listed some features in Alpha state, however some of them are qualified already and also deployed in production setups.  we have to lift these features from Alpha/Beta to Beta/GA state in upcoming Ceph CSI releases. 

`RBD`

||Features   | Feature Status | CSI Driver Version | CSI Spec Version | Ceph Cluster Version | Kubernetes Version |
| ------ | --------------------------------------------------------- | -------------- | ------------------ | ---------------- | -------------------- | ------------------ |
|Provision File Mode ROX volume from snapshot              | Alpha          | >= v3.0.0          | >= v1.0.0        | Nautilus (>=v14.2.2) | >= v1.17.0         |
| Provision File Mode ROX volume from another volume        | Alpha          | >= v3.0.0          | >= v1.0.0        | Nautilus (>=v14.2.2) | >= v1.16.0         |
 | Provision Block Mode ROX volume from snapshot             | Alpha          | >= v3.0.0          | >= v1.0.0        | Nautilus (>=v14.2.2) | >= v1.17.0         |
| Provision Block Mode ROX volume from another volume       | Alpha          | >= v3.0.0          | >= v1.0.0        | Nautilus (>=v14.2.2) | >= v1.16.0         |
 | Creating and deleting snapshot                            | Alpha          | >= v1.0.0          | >= v1.0.0        | Nautilus (>=14.0.0)  | >= v1.17.0         |
| Provision volume from snapshot                            | Alpha          | >= v1.0.0          | >= v1.0.0        | Nautilus (>=14.0.0)  | >= v1.17.0         |
| Provision volume from another volume                      | Alpha          | >= v1.0.0          | >= v1.0.0        | Nautilus (>=14.0.0)  | >= v1.16.0         |
| Expand volume                                             | Beta           | >= v2.0.0          | >= v1.1.0        | Nautilus (>=14.0.0)  | >= v1.15.0         |
| Metrics Support                                           | Beta           | >= v1.2.0          | >= v1.1.0        | Nautilus (>=14.0.0)  | >= v1.15.0         |
 Topology Aware Provisioning Support                       | Alpha          | >= v2.1.0          | >= v1.1.0        | Nautilus (>=14.0.0)  | >= v1.14.0         |

`CephFS`

||Features                                                  | Feature Status | CSI Driver Version | CSI Spec Version | Ceph Cluster Version | Kubernetes Version |
| ------ | --------------------------------------------------------- | -------------- | ------------------ | ---------------- | -------------------- | ------------------ |
| Dynamically provision, de-provision File mode RWO volume  | Beta           | >= v1.1.0          | >= v1.0.0        | Nautilus (>=14.2.2)  | >= v1.14.0         |
| Dynamically provision, de-provision File mode RWX volume  | Beta           | >= v1.1.0          | >= v1.0.0        | Nautilus (>=v14.2.2) | >= v1.14.0         |
| Dynamically provision, de-provision File mode ROX volume  | Alpha          | >= v3.0.0          | >= v1.0.0        | Nautilus (>=v14.2.2) | >= v1.14.0         |
|Creating and deleting snapshot                            | Alpha          | >= v3.1.0          | >= v1.0.0        | Octopus (>=v15.2.3)  | >= v1.17.0         |
|  Provision volume from snapshot                            | Alpha          | >= v3.1.0          | >= v1.0.0        | Octopus (>=v15.2.3)  | >= v1.17.0         |
| Provision volume from another volume                      | Alpha          | >= v3.1.0          | >= v1.0.0        | Octopus (>=v15.2.3)  | >= v1.16.0         |
| Expand volume                                             | Beta           | >= v2.0.0          | >= v1.1.0        | Nautilus (>=v14.2.2) | >= v1.15.0         |
| Metrics                                                   | Beta           | >= v1.2.0          | >= v1.1.0        | Nautilus (>=v14.2.2) | >= v1.15.0         |

Above is the list of features at the moment stays on `Alpha` or `Beta`:

It is good to have one tracker for each for better tracking..etc.  Will add the separate tracker and update this issue.

The promotion criteria :

-  [x] Make sure the referenced feature is covered in the documentation
-  [x] Make sure we have E2E test available for the feature
-  [x] Track each feature in a separate issue with priority set
-  [x] update the status of the feature in support matrix documentation  if we covered all of the above for a feature

@Madhu-1 @nixpanic @agarwal-mudit  @Yuggupta27 @Rakshith-R @yati1998 @pkalever please let me know if I missed any criteria for the promotion of the feature and we need volunteers :)

**[update 2-2-2022] Release 3.5** 

*Beta*:
- [x] Expand Volume for RBD and CephFS

*GA*: 
- [x] Creation and deletion of  RBD and CephFS Snapshot  #2304 
- [x] Volume creation from snapshot or restore of snapshot functionality of  RBD and CephFS  #2304  
- [x] Volume creation from PVC or clone functionality of  RBD and CephFS  #2304  
- [x] PV metrics for RBD ( Filemode and Block) and CephFS

**Comment by humblec** [comment]
As discussed we have to continue the analysis and get into the completion in upcoming releases. Moving this out of 3.4.0 release.

**Comment by humblec** [comment]
Topology was the main feature which we were looking into promoting to Beta.. It has made good progress, however we may have to keep it in alpha in release 3.6 . I am moving this issue to next release tracker for now.
