### ISSUE TITLE
Tracker issue for intree rbd to ceph csi online migration

### ISSUE THREAD

**Issue by humblec** [ceph/ceph-csi#2509]
# Describe the bug #

This issue track the few changes required to support in tree rbd migration to ceph csi ( Project # https://github.com/ceph/ceph-csi/projects/18) , this allows an in tree rbd user to do  online migration without changing any existing templates. This feature is tracked in kubernetes for v1.23 as alpha under https://github.com/kubernetes/enhancements/pull/2963. 

Demo : part 1 shows PVCs created before enabling migration and part2 shows PVCs created after migration. 
https://drive.google.com/file/d/1yfcngCEyrOPDG5tOg7gva0wVJqNELRGc/view

As discussed in CSI calls, currently identified changes are:

- [x] Get clusterid from mon #https://github.com/ceph/ceph-csi/pull/2512
- considering the clusterID field is a required one for csi , but intree SC has monitors field as a required thing we have to figure out the clusterID from the monitors passed in the request.  The node stage and unstage operations should work without any issues as those will be tracked as static volumes for the csi driver.
- [x] Use a volume handle passed in and use it for operations on existing volumes. #https://github.com/ceph/ceph-csi/pull/2523
The volume handle would include the migration version, mon, pool and image which could be used for operations like delete. Once we have these information available with us its well possible to delete the existing in tree PVs. The volume handle can 
The current format of the volume handle looks like this:

```
mig_mons-<monitors-hash>_image-<imagename>_<pool-hash>
```
Admin supposed to create a clusterID based on the monitors hash ( md5sum) in the csi config map and keep the monitors under this configuration before enabling the migration. While CSI driver receive the volume handle it will look at the configmap and figure out the mons to do the operations.  
- [x] use/fill required secret data in the incoming migration secret request #https://github.com/ceph/ceph-csi/pull/2562

The initial plan was to ask the admin to adjust the secret as a pre-upgrade step for migration which avoid this change in the CSI driver, however taking out admin burden is the main ask from kubernetes community so this change is introduced.
"key" field value will be picked up from the migraion secret to "UserKey" field. "adminId" field value will be picked up from the migration secret to "UserID" field.  if `adminId` field is nil or not set, `UserID` field will be filled with default value ie `admin`.The above logic get activated only when the secret is a migration secret, otherwise skipped to the normal workflow as we have today.

ToDo:
- [x] Add design documentation #2609 
- [x] Validate or add NBD case accordingly.  
  - while doing so, e2e static test cases can also be changed to take a mounter arg, for more flexibility of checking
- [x]  Change nodestage operation to use mons hash and get rid of getClusterID from mon operation. #2557  [introduced as part of PR review comment]
- [x]  add migration secret code change in controller server for a couple more (ex: expand,create) functions. #https://github.com/ceph/ceph-csi/pull/2648
- [x] remove with error and add helpers for migration e2e tests  
- [x] Enable resize for intree volumes. #2741
- [x] recreateRBDPods e2e function can be made general.  [introduced as part of PR review comment] #2748 
- [x] Add documentation with examples #https://github.com/ceph/ceph-csi/pull/2765
https://github.com/ceph/ceph-csi/issues/1725
- [ ] remove E2E hacks and do valid migration testing with Kubernetes 1.23 as its released.

Release 3.6 Items:
- [x] Validate or support inline volumes
- [ ] CephFS online migration

**Comment by Madhu-1** [comment]
@humblec any specific reason not to use/suggest the CSI migration tool which is getting developed by @Yuggupta27 and @subhamkrai? 

>get clusterid from mon
 use a volume handle passed in and support static volume mounting, unmounting, and delete operations on existing volumes.

IMO This is an extra burden to the cephcsi supportability point of view


can you please provide more details with examples of why we are taking this approach?

**Comment by humblec** [comment]
> @humblec any specific reason not to use/suggest the CSI migration tool which is getting developed by @Yuggupta27 and @subhamkrai?

@Madhu-1 For `offline migration` ( taking down the app and untangling from pvc and attaching old pv after renaming to new pvc)  , the  tool can also be used,   as mentioned in the issue, this is an `online` migration for existing in tree users, the users will be capable to continue using the templates as they do today and everything will be taken care by the kubernetes, they dont want to change any existing templates like `SC, PVC`...etc . They will be unaware that, the migration is happening ...etc, thats why the migration framework in kubernetes (https://github.com/kubernetes/kubernetes/pull/95361) becomes handy.  Most of the kube intree drivers have been migrated or more are in migration path.

At any point they want to do offline migration , they could make use of the tool as well..  so users are left with good amount of choices and have options for both online and offline migration and make use of Ceph CSI. !!


> 
> > get clusterid from mon
> > use a volume handle passed in and support static volume mounting, unmounting, and delete operations on existing volumes.
> 
> IMO This is an extra burden to the cephcsi supportability point of view

I dont think so,  these helpers will be ONLY called for `migrated volumes` and while csi driver process those , that too with very limited usage like mount , unmount ..etc.  Its is same as we currently support static volumes today.  None of the existing functionality would be broken with this change , so it shouldnt be a burden. Also snapshot , cloning ..etc are not supported on these static kind of volumes. 

> 
> can you please provide more details with examples of why we are taking this approach?

The intree driver has `monitor` field available with it, so our configmap can be read to get the clusterid if its a migration request.  Almost like we do read clusterid mapping for replication cases...etc. 
Once the clusterID is available , rest of the information is available for continuing to support it as static volume. 
the volume handle would be same as our static volume case but just got a couple of strings append to it which carry the monitor and pool in it , very bare minimum stuff without any fancy operations on it.

**Comment by Madhu-1** [comment]
>I dont think so, these helpers will be ONLY called for migrated volumes and while csi driver process those , that too with very limited usage like mount , unmount ..etc. Its is same as we currently support static volumes today. None of the existing functionality would be broken with this change , so it shouldnt be a burden. Also snapshot , cloning ..etc are not supported on these static kind of volumes.

yes if we go for offline tools we can support all these features.

>I dont think so, these helpers will be ONLY called for migrated volumes and while csi driver process those , that too with very limited usage like mount , unmount ..etc. Its is same as we currently support static volumes today. None of the existing functionality would be broken with this change , so it shouldnt be a burden. Also snapshot , cloning ..etc are not supported on these static kind of volumes.


we don't support DeleteVolume for the static PVC but you have added it to the list. as I already mentioned in https://github.com/ceph/ceph-csi/issues/1725#issuecomment-823225160 not sure it's worth supporting this one with extra effort.

If we really need/want to support this one please  make sure we support only the ceph version mentioned in the readme

**Comment by humblec** [comment]
> > I dont think so, these helpers will be ONLY called for migrated volumes and while csi driver process those , that too with very limited usage like mount , unmount ..etc. Its is same as we currently support static volumes today. None of the existing functionality would be broken with this change , so it shouldnt be a burden. Also snapshot , cloning ..etc are not supported on these static kind of volumes.
> 
> yes if we go for offline tools we can support all these features.

Yep, iow, at any point in time ( even after online migration has been enabled) , if users want to go with offline migration (now or  later or even only for few volumes) , they can take that route based on the production downtime and feasibility of making other changes for the  consumers of current volumes and its templates.  

Online can be an intermediate path as well for many deployments.

> 
> > I dont think so, these helpers will be ONLY called for migrated volumes and while csi driver process those , that too with very limited usage like mount , unmount ..etc. Its is same as we currently support static volumes today. None of the existing functionality would be broken with this change , so it shouldnt be a burden. Also snapshot , cloning ..etc are not supported on these static kind of volumes.
> 
> we don't support DeleteVolume for the static PVC but you have added it to the list. as I already mentioned in [#1725 (comment)](https://github.com/ceph/ceph-csi/issues/1725#issuecomment-823225160) not sure it's worth supporting this one with extra effort.
> 

As this delete will be only for "migration volumes" it will be a very shim helper function and can be done with it. 


> If we really need/want to support this one please make sure we support only the ceph version mentioned in the readme

Sure @Madhu-1 , thats the plan :+1:

**Comment by Madhu-1** [comment]
@humblec I have added one more todo to `Remove E2E hacks and do valid migration testing with Kubernetes 1.23 as its released`
