### ISSUE TITLE
Release 3.6.0 tracker issue

### ISSUE THREAD

**Issue by humblec** [ceph/ceph-csi#2826]
# Describe the feature you'd like to have #

This issue tracks 3.6 release of Ceph CSI driver. Lets gather the features and plan the release.

- **Proposed release date**
- [x] Code Freeze: 30-Mar-2022
- [x] GA               : 04-Apr-2022

- **Features:**

- [x] Detect corrupted FUSE mounts and restore them  : Owner @gman0
- [ ] Cephfs: efficient read-only snapshots as volumes : Owner @gman0   
- [x] Enable CephFS encryption :  Owner @irq0

- **Bug fixes:**
- **Enhancements:**
#2059
#2190
#250
#2015
#2371
#1619
#2509
#2823

Cc @ceph/ceph-csi-maintainers  @ceph/ceph-csi-contributors

**Comment by Madhu-1** [comment]
Am proposing below lits of issues that are important and moved out of a couple of releases

https://github.com/ceph/ceph-csi/issues/2059
https://github.com/ceph/ceph-csi/issues/2190
https://github.com/ceph/ceph-csi/issues/250
https://github.com/ceph/ceph-csi/issues/2015
https://github.com/ceph/ceph-csi/issues/2371
https://github.com/ceph/ceph-csi/issues/1619

**Comment by nixpanic** [comment]
What is the goal of this release? Can it be described as a topic in the milestone please? At the moment, I have the feeling it can called something like _improved testing and bugfixes_?

If there is a goal for the release, it makes it clearer what features can get included, and what will be moved out to the next release. There are currently 17 open issues/PRs attached to the milestone, and getting all of them addressed before the end of March already looks like a stretch to me.

**Comment by humblec** [comment]
Sure, let me update with the goal/theme of the release , thanks for the suggestion :+1:

**Comment by humblec** [comment]
@ceph/ceph-csi-contributors any features you want to propose for Release 3.6 ?

**Comment by humblec** [comment]
Cc @gman0 @irq0

**Comment by gman0** [comment]
@humblec maybe we could do "best effort" on https://github.com/ceph/ceph-csi/issues/2142 as well? I'm two PRs away to finish the work for go-ceph (already pushed and the folks there reviewing diligently) -- seems like go-ceph v0.14.0 will be out right after, so this might be doable.

**Comment by humblec** [comment]
> @humblec maybe we could do "best effort" on #2142 as well? I'm two PRs away to finish the work for go-ceph (already pushed and the folks there reviewing diligently) -- seems like go-ceph v0.14.0 will be out right after, so this might be doable.

Sure @gman0 , That will be a great addition to the project! 

Added to the features list :+1:

**Comment by humblec** [comment]
[update]
we will close the items by 01-Apr-2022 and planning to release on 04-Apr-2022

**Comment by gman0** [comment]
I've moved https://github.com/ceph/ceph-csi/issues/2142 for the next release.

**Comment by humblec** [comment]
Considering we have 3.6.0 out, I am closing this issue

https://github.com/ceph/ceph-csi/releases/tag/v3.6.0 

Thanks all for your contributions to 3.6 !!  :+1:
