### ISSUE TITLE
Provisioning of NFS exported volumes

### ISSUE THREAD

**Issue by nixpanic** [ceph/ceph-csi#2913]
# Describe the feature you'd like to have #

It would be useful to have volumes provisioned that can be exported over NFS. Ceph already has the ability to [manage NFS-Ganesha and export CephFS directories (or subvolumes)](https://docs.ceph.com/en/latest/mgr/nfs/).

# What is the value to the end user? (why is it a priority?) #

This would allow the following use-cases to be addressed:

- clients that can not reach the OSDs/MONs, but could use a single TCP-port to connect to the Ceph managed NFS-server
- worker-nodes that do not have support for CephFS (NFS is more standard)

# How will we know we have a good solution? (acceptance criteria) #

Minimally the following CSI operations should be supported:

- `CreateVolume`
- `DeleteVolume`

# Proof of Concept #

A [work-in-progress NFS-provisioner](https://github.com/nixpanic/ceph-csi/tree/wip/nfs-provisioner) is available, with a container image at `quay.io/nixpanic/cephcsi:nfs`. Changes/additions are mostly under `internal/nfs/` and `examples/nfs/`. Scripts and .yaml deployment files are included in the branch for testing and deploying with Rook. (Testing is done on OpenShift Data Foundation, as those deployments are readily available to me.)

# Tasks #

- [x] design document: #2914
- [x] NFS-provisioner component: #2948
- [x] deployment artifacts: #2980
- [x] e2e testing: #3036
- [ ] validate error handling, CSI-procedures should be idempotent
  - [ ] `CreateVolume`
  - [x] `DeleteVolume`: #3071
- [x] use go-ceph API instead of `ceph` command: #2977, ceph/go-ceph#655
- [ ] documentation
- [ ] deployment with helm
- [ ] examples: #2963

**Comment by Rakshith-R** [comment]
items are still yet to be done.
