### ISSUE TITLE
Release 3.8.0 tracker

### ISSUE THREAD

**Issue by humblec** [ceph/ceph-csi#3336]
# Describe the bug #

This issue tracks release v3.8 of Ceph CSI driver 
The milestone is available here https://github.com/ceph/ceph-csi/milestone/15

- [ ] Code Freeze : 10 Feb 2023
- [ ] GA : 15 Feb 2023

Features:
- [x] #3310 
- [x] read_from_replica support for better performance @Rakshith-R 
- [x] https://github.com/ceph/ceph-csi/issues/757 
- [x] https://github.com/ceph/ceph-csi/issues/3603
- [x] https://github.com/ceph/ceph-csi/issues/3616
- [x] https://github.com/ceph/ceph-csi/issues/2637 
- [x] https://github.com/ceph/ceph-csi/pull/3639

**Comment by humblec** [comment]
@ceph/ceph-csi-contributors any features we would like to track it for this release ? If yes, please list out

**Comment by yati1998** [comment]
https://github.com/ceph/ceph-csi/issues/3603 ?

**Comment by humblec** [comment]
> #3603 ?

Yeah , thanks ! added

**Comment by Rakshith-R** [comment]
Release notes regarding read affinity and 
removal of option to run cephcsi being run as both controller and node servers when either of the option is provided.
https://github.com/ceph/ceph-csi/pull/3639#discussion_r1095685719

**Comment by humblec** [comment]
> Release notes regarding read affinity and removal of option to run cephcsi being run as both controller and node servers when either of the option is provided. [#3639 (comment)](https://github.com/ceph/ceph-csi/pull/3639#discussion_r1095685719)

Sure.. added on the tracker

**Comment by humblec** [comment]
@riya-singhal31 are we targetting shallow volumes for 3.8 ?

**Comment by riya-singhal31** [comment]
> @riya-singhal31 are we targetting shallow volumes for 3.8 ?

Yes

**Comment by Madhu-1** [comment]
Closing as the 3.8 release is out, and @Rakshith-R will take care of creating new milestone, and issue trackers for 3.9
