### ISSUE TITLE
Rebase to latest module dependencies - Ceph-CSI v3.8 version tracker

### ISSUE THREAD

**Issue by humblec** [ceph/ceph-csi#3616]
- [x] Latest rook consumtion
- [x] go-ceph release
- [x] Kubernetes release 
- [x] sidecars
- [x] other possible module updates

**Comment by Madhu-1** [comment]
I am closing as updated kubernetes to 1.26
