### ISSUE TITLE
Add external-storage tests for nfs 

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#4540]
We have external-storage tests for cephfs https://github.com/ceph/ceph-csi/tree/devel/scripts/k8s-storage not for nfs, This is a tracker for nfs tests
```[tasklist]
### Tasks
- [ ] add `driver-nfs.yaml` in `scripts/k8s-storage` directory
- [ ] add `sc-nfs.yaml.in` in `scripts/k8s-storage` directory
- [ ] verify the output of a manual trigger CI run that NFS tests are executed
```

**Comment by AryanSwaroop** [comment]
Can this issue be assigned to me if no one is working on it !!

**Comment by nixpanic** [comment]
> Can this issue be assigned to me if no one is working on it !!

Sure! Thank you for having a go at it.

**Comment by AryanSwaroop** [comment]
Sure, I'll try my best to resolve this !

**Comment by AryanSwaroop** [comment]
@nixpanic how much time do I get for resolving this issue ?

**Comment by AtulBoyal** [comment]
Hi, I’d love to work on this issue as my first contribution. Is it still available? If so, I’d like to start working on it!
